// NOTE: This file is generated by uniwind and it should not be edited manually.
/// <reference types="uniwind/types" />

declare module 'uniwind' {
    export interface UniwindConfig {
        themes: readonly ["light", "dark", "grove-light", "grove-dark", "ocean-light", "ocean-dark", "ember-light", "ember-dark", "iris-light", "iris-dark", "midnight-light", "midnight-dark", "graphite-light", "graphite-dark", "canvas-light", "canvas-dark", "paper-light", "paper-dark"]
    }
}

export {}
